// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eukerxgmcsonyuypgniy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV1a2VyeGdtY3Nvbnl1eXBnbml5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUwMzA0MDcsImV4cCI6MjA2MDYwNjQwN30.EmBZbsy1lYiA1g-bXU-ZT4enn0VSE8-CXQGgmQ1eWzc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);